# GNU Make workspace makefile autogenerated by Premake

.NOTPARALLEL:

ifndef config
  config=release
endif

ifndef verbose
  SILENT = @
endif

ifeq ($(config),release)
  Anim2_config = release
  GLFW_config = release
  GLAD_config = release
endif
ifeq ($(config),debug)
  Anim2_config = debug
  GLFW_config = debug
  GLAD_config = debug
endif

PROJECTS := Anim2 GLFW GLAD

.PHONY: all clean help $(PROJECTS) 

all: $(PROJECTS)

Anim2: GLFW GLAD
ifneq (,$(Anim2_config))
	@echo "==== Building Anim2 ($(Anim2_config)) ===="
	@${MAKE} --no-print-directory -C Anim2 -f Makefile config=$(Anim2_config)
endif

GLFW:
ifneq (,$(GLFW_config))
	@echo "==== Building GLFW ($(GLFW_config)) ===="
	@${MAKE} --no-print-directory -C Anim2/Vendor/glfw -f Makefile config=$(GLFW_config)
endif

GLAD:
ifneq (,$(GLAD_config))
	@echo "==== Building GLAD ($(GLAD_config)) ===="
	@${MAKE} --no-print-directory -C Anim2/Vendor/glad -f Makefile config=$(GLAD_config)
endif

clean:
	@${MAKE} --no-print-directory -C Anim2 -f Makefile clean
	@${MAKE} --no-print-directory -C Anim2/Vendor/glfw -f Makefile clean
	@${MAKE} --no-print-directory -C Anim2/Vendor/glad -f Makefile clean

help:
	@echo "Usage: make [config=name] [target]"
	@echo ""
	@echo "CONFIGURATIONS:"
	@echo "  release"
	@echo "  debug"
	@echo ""
	@echo "TARGETS:"
	@echo "   all (default)"
	@echo "   clean"
	@echo "   Anim2"
	@echo "   GLFW"
	@echo "   GLAD"
	@echo ""
	@echo "For more information, see https://github.com/premake/premake-core/wiki"